import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

// A draft only needs `draft: true` — nothing else is checked, so an
// unfinished post can never break the build. Once `draft` is false/absent,
// the full schema applies.
const draftSchema = z.object({
	draft: z.literal(true),
	title: z.string().optional(),
	description: z.string().optional(),
	pubDate: z.coerce.date().optional(),
	updatedDate: z.coerce.date().optional(),
});

const publishedSchema = z.object({
	draft: z.literal(false).optional(),
	title: z.string(),
	description: z.string(),
	// Transform string to Date object
	pubDate: z.coerce.date(),
	updatedDate: z.coerce.date().optional(),
});

const blog = defineCollection({
	// Load Markdown and MDX files in the `src/content/blog/` directory.
	loader: glob({ base: './src/content/blog', pattern: '**/*.{md,mdx}' }),
	schema: z.union([draftSchema, publishedSchema]),
});

const pages = defineCollection({
	loader: glob({ base: './src/content/pages', pattern: '**/*.{md,mdx}' }),
	schema: z.object({
		title: z.string(),
		description: z.string(),
	}),
});

// Machine-translated posts/pages, generated by scripts/translate-posts.mjs.
// sourceHash lets that script detect whether the German source has changed
// since a given language was last translated. One collection pair per
// language in src/utils/i18n.ts's LANGUAGES list.
function translatedBlog(dir) {
	return defineCollection({
		loader: glob({ base: dir, pattern: '**/*.{md,mdx}' }),
		schema: z.object({
			title: z.string(),
			description: z.string(),
			pubDate: z.coerce.date(),
			updatedDate: z.coerce.date().optional(),
			sourceHash: z.string(),
		}),
	});
}

function translatedPages(dir) {
	return defineCollection({
		loader: glob({ base: dir, pattern: '**/*.{md,mdx}' }),
		schema: z.object({
			title: z.string(),
			description: z.string(),
			sourceHash: z.string(),
		}),
	});
}

export const collections = {
	blog,
	pages,
	blogEn: translatedBlog('./src/content/blog-en'),
	pagesEn: translatedPages('./src/content/pages-en'),
	blogZh: translatedBlog('./src/content/blog-zh'),
	pagesZh: translatedPages('./src/content/pages-zh'),
	blogHi: translatedBlog('./src/content/blog-hi'),
	pagesHi: translatedPages('./src/content/pages-hi'),
	blogEs: translatedBlog('./src/content/blog-es'),
	pagesEs: translatedPages('./src/content/pages-es'),
	blogFr: translatedBlog('./src/content/blog-fr'),
	pagesFr: translatedPages('./src/content/pages-fr'),
	blogAr: translatedBlog('./src/content/blog-ar'),
	pagesAr: translatedPages('./src/content/pages-ar'),
	blogRu: translatedBlog('./src/content/blog-ru'),
	pagesRu: translatedPages('./src/content/pages-ru'),
};
